name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        echo "${{ secrets.EC2_KEY }}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}
    - name: Deploy via SSH
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          if [ -d ~/Modern_Data_Analytics ]; then
            cd ~/Modern_Data_Analytics
            if [ ! -d .git ]; then
              echo "Directory exists but is not a git repo. Removing and cloning afresh."
              cd ~
              rm -rf Modern_Data_Analytics
              git clone https://github.com/David-TMNg/Modern_Data_Analytics.git
              cd Modern_Data_Analytics
            else
              git pull origin main
            fi
          else
            git clone https://github.com/David-TMNg/Modern_Data_Analytics.git
            cd Modern_Data_Analytics
          fi

          docker stop shiny-app || true
          docker rm shiny-app || true
          docker build -t shiny-python-app .
          docker run -d --name shiny-app -p 80:8000 shiny-python-app
        EOF
