name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > private_key
        chmod 600 private_key

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          cd ~
          rm -rf Modern_Data_Analytics
          git clone --branch main https://github.com/David-TMNg/Modern_Data_Analytics.git
          cd Modern_Data_Analytics

          docker stop shiny-app || true
          docker rm shiny-app || true
          docker system prune -a --volumes -f
          docker build -t shiny-python-app .
          docker run -d --name shiny-app -p 80:8000 shiny-python-app
        EOF
